### ISSUE TITLE
merge的注意事項

### ISSUE THREAD

**Issue by bryanyang0528** [TaiwanSparkUserGroup/spark-programming-guide-zh-tw#17]
https://github.com/doggy8088/Learn-Git-in-30-days/blob/master/docs/17%20%E9%97%9C%E6%96%BC%E5%90%88%E4%BD%B5%E7%9A%84%E5%9F%BA%E6%9C%AC%E8%A7%80%E5%BF%B5%E8%88%87%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F.markdown

之後把這段加到Contributing裡面

**Comment by bryanyang0528** [comment]
我加了~

**Comment by jhowliu** [comment]
如果要幫忙翻譯的話直接開Issue嗎

**Comment by ChuyuHsu** [comment]
@jhowliu 是的直接開ISSUE就好

**Comment by jhowliu** [comment]
@ChuyuHsu Ok

**Comment by bryanyang0528** [comment]
@jhowliu  感謝~有問題隨時發ISSUE唷，因為這篇的主題已經OK，我就把這篇關掉了
