### ISSUE TITLE
Translate Machine Learning Library (MLlib) Programming Guide

### ISSUE THREAD

**Issue by ChuyuHsu** [TaiwanSparkUserGroup/spark-programming-guide-zh-tw#27]
Yes, there's one more chapter the official Apache Spark site provides
But I don't think I can do it on my own
ref:
https://spark.apache.org/docs/latest/mllib-guide.html

**Comment by bryanyang0528** [comment]
分一點來阿~

**Comment by ChuyuHsu** [comment]
當然啊 我沒辦法全翻XDDD

**Comment by bryanyang0528** [comment]
把正在翻的在這篇推一下好了～

**Comment by ChuyuHsu** [comment]
好的 當我開始的時候會開ISSUE

**Comment by bryanyang0528** [comment]
@youngce  動作超快~可以把正在翻譯的章節放到ISSUE來，比較不會重覆翻譯到~
