### ISSUE TITLE
programming-guide翻譯中

### ISSUE THREAD

**Issue by wlsherica** [TaiwanSparkUserGroup/spark-programming-guide-zh-tw#39]
programming-guide翻譯中

**Comment by wlsherica** [comment]
....pull request bottom再度不見orz
我每次push前都會做下列動作：
git remote update
git fetch upstream master
git checkout master
git rebase upstream/master
git pull
再做add -> commit -> push

最新一次push：
erica_li@cdh4-dn2 rdds]$ git push
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 504 bytes, done.
Total 5 (delta 4), reused 0 (delta 0)
To git@github.com:wlsherica/spark-programming-guide-zh-tw.git
   e84e033..4613d33  develop -> develop

是不是漏什麼？

**Comment by bryanyang0528** [comment]
奇怪~應該是不會有衝突，除非就是自己的push和自己的push互相衝突@@

我的流程是(假設remote設好，當下位置是在master，還沒開新的branch)
`git fetch upstream master`
`git merge upstream/master`
這時候master是最新的

然後開新的branch
`git checkout -b newbranch`

~coding~
`git add`
`git commit`
`git push origin newbranch`
然後發PR

如果PR還沒有人merge，我就會另外在開新的branch放另外一個文章的更新檔

**Comment by wlsherica** [comment]
請教，那～branch開好以後應該就一直是在該branch下活動對吧？
Bryan這段流程與CONTRIBUTING.rst好像有點不同？

首先 fork 我的項目(在專案畫面右上角)
把 fork 過去的項目也就是你的項目 clone 到你的本機端
在命令行運行 git branch develop 來創建一個新分支
運行 git checkout develop 來切換到新分支
運行 git remote add upstream https://github.com/TaiwanSparkUserGroup/spark-programming-guide-zh-tw.git 把我的庫添加為遠端庫
運行 `git remote update`更新
運行 git fetch upstream master 拉取我的庫的更新到本地
運行 git rebase upstream/master 將我的更新合並到你的分支
這是一個初始化流程，只需要做一遍就行，之後請一直在 develop 分支進行修改。
如果修改過程中我的庫有了更新，請重復 6、7、8 步。

我在另外一個folder重做一次：
1. 先git clone git@github.com:wlsherica/spark-programming-guide-zh-tw.git
2. git remote add upstream https://github.com/TaiwanSparkUserGroup/spark-programming-guide-zh-tw.git
3. git fetch upstream master
4. git merge upstream/master 

> fatal: 'upstream/master' does not point to a commit

**Comment by bryanyang0528** [comment]
OK 我懂了 我把中間過程寫詳細一點

**Comment by wlsherica** [comment]
對了！README.md裡面的貢獻方式連結點出去是404喔！Thanks

**Comment by bryanyang0528** [comment]
OK@@ 我再修

**Comment by wlsherica** [comment]
programming-guide 資料夾內的翻譯完畢等待merge
